spring.application.name=palant_ventas

# MySQL Connection (Update username and password as needed)
spring.datasource.url=jdbc:mysql://localhost:3306/palant_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion para subir imagenes mas grandes (Banners/Vouchers)
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Thymeleaf cache for DevTools
spring.thymeleaf.cache=false

# Port
server.port=8080
